import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/page";

export const metadata: Metadata = {
  title: "Início | Kauan Moreira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
